### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Lekkit-code** [dotchetter/RobBotTheRobot#8]
Give the bot an email adress that's in the IoT19 distribution mailing list. Then make sure he can tell everyone that there's a new mail, or read the mail out lout. Like a herald of old times.

**Comment by dotchetter** [comment]
This issue is currently being investigated in order for GDPR and compliance with the privacy policy of the institute, in consultation with the head of IT at the institute.

**Comment by dotchetter** [comment]
Unable to comply with privacy policies at the institute.
